services:
  - type: web
    name: ge-bot-1-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
