-- =============================================
-- MEO VB1 Smart Farm Database Schema
-- SQLite3 Database
-- =============================================

-- Users Table: Stores admin and farmer accounts
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,           -- bcrypt hashed
    role TEXT NOT NULL DEFAULT 'user', -- 'admin' or 'user'
    full_name TEXT DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME
);

-- Sensor Data Table: Stores all sensor readings
CREATE TABLE IF NOT EXISTS sensor_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    temperature REAL DEFAULT 0,
    moisture REAL DEFAULT 0,
    battery REAL DEFAULT 0,
    health REAL DEFAULT 0,
    humidity REAL DEFAULT 0,
    wind_speed REAL DEFAULT 0,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Logs Table: System activity logs
CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    action TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'system', -- command/event/alert/system
    message TEXT DEFAULT '',
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Robot State Table: Current robot position and mode
CREATE TABLE IF NOT EXISTS robot_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    robot_x REAL DEFAULT 25,
    robot_y REAL DEFAULT 25,
    mode TEXT DEFAULT 'Patrol',
    location TEXT DEFAULT 'A',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert default admin user (password: admin123)
-- Hash will be generated by database.js on first run

-- Insert default robot state
INSERT OR IGNORE INTO robot_state (id, robot_x, robot_y, mode, location) 
VALUES (1, 25, 25, 'Patrol', 'A');
